# Generated by Django 2.2 on 2020-04-16 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status post', 'verbose_name_plural': 'Status posts'},
        ),
        migrations.AlterModelManagers(
            name='status',
            managers=[
            ],
        ),
    ]
